{{- $podDisruptionBudget := index .Values "podDisruptionBudgets" "weaviate" -}}
{{- if index $podDisruptionBudget "enabled" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "weaviate.fullname" . }}
  labels:
    name: {{ include "weaviate.fullname" . }}
    app: {{ include "weaviate.fullname" . }}
    app.kubernetes.io/name: {{ include "weaviate.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "weaviate.fullname" . }}
  {{- toYaml $podDisruptionBudget.spec | nindent 2 }}
{{- end -}}
