{{ if .Values.runtime_overrides.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weaviate.fullname" . }}-runtime-overrides
  labels:
    app.kubernetes.io/name: {{ include "weaviate.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  overrides.yaml: |-
    {{- if .Values.runtime_overrides.values }}
    {{ .Values.runtime_overrides.values | toYaml | nindent 4 }}
    {{- end }}

{{ end }}
