apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-headless
  labels:
    app.kubernetes.io/name: {{ include "weaviate.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ include "weaviate.fullname" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.env.CLUSTER_GOSSIP_BIND_PORT }}
  publishNotReadyAddresses: true
