{{- if .Values.auth.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weaviate.fullname" . }}
  labels:
    {{- include "weaviate.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.auth.apiKey | b64enc }}
{{- end }}
